apiVersion: webapp.hellofromtheinternet.hu/v0
kind: MyWebapp
metadata:
  name: mywebapp-sample
spec:
  # Add fields here
  replicas: 4
  host: hellofromtheinternet.hu
  email: jakyandras@gmail.com
  image: nginx:1.20.1
