# permissions for end users to edit mywebapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mywebapp-editor-role
rules:
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps/status
  verbs:
  - get
