# permissions for end users to view mywebapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mywebapp-viewer-role
rules:
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps/status
  verbs:
  - get
