
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.hellofromtheinternet.hu
  resources:
  - mywebapps/status
  verbs:
  - get
  - patch
  - update
